import 'package:flutter/material.dart';

/* UndefinedNode Masuk Guest
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMasukGuestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
