import 'package:flutter/material.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedFrozenFoodBaksoLurahWidget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedImage3Widget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedGroup176Widget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedGroup196Widget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedFrozenFoodTempuraFoodyWidget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedImage19Widget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedTempuraFoodyWidget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedGroup166Widget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedImage3Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedGroup197Widget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedBaksoLurahWidget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedGroup130Widget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedGroup201Widget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedTempuraFoodyBerat500gramWidget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedGroup129Widget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedProdukWidget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedImage18Widget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedGroup200Widget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedFuterWidget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedBaksocurahBerat500gramWidget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedHeaderWidget.dart';
import 'package:flutterapp/frezzemeapp/generated4homepageuserwidget/generated/GeneratedImage20Widget.dart';

/* Frame 4. HomePage user
    Autogenerated by FlutLab FTF Generator
  */
class Generated4HomePageuserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1112.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 1112.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 255, 255, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 190.0,
                                    top: 110.0,
                                    right: null,
                                    bottom: null,
                                    width: 160.0,
                                    height: 210.0,
                                    child: GeneratedGroup129Widget(),
                                  ),
                                  Positioned(
                                    left: 10.0,
                                    top: 340.0,
                                    right: null,
                                    bottom: null,
                                    width: 160.0,
                                    height: 210.0,
                                    child: GeneratedGroup130Widget(),
                                  ),
                                  Positioned(
                                    left: 12.0,
                                    top: 73.0,
                                    right: null,
                                    bottom: null,
                                    width: 77.0,
                                    height: 29.0,
                                    child: GeneratedProdukWidget(),
                                  ),
                                  Positioned(
                                    left: 200.0,
                                    top: 118.0,
                                    right: null,
                                    bottom: null,
                                    width: 87.0,
                                    height: 19.0,
                                    child: GeneratedBaksoLurahWidget(),
                                  ),
                                  Positioned(
                                    left: 19.0,
                                    top: 348.0,
                                    right: null,
                                    bottom: null,
                                    width: 108.0,
                                    height: 19.0,
                                    child: GeneratedTempuraFoodyWidget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 499.0,
                                    right: null,
                                    bottom: null,
                                    width: 132.0,
                                    height: 13.0,
                                    child:
                                        GeneratedFrozenFoodTempuraFoodyWidget(),
                                  ),
                                  Positioned(
                                    left: 10.0,
                                    top: 110.0,
                                    right: null,
                                    bottom: null,
                                    width: 177.0,
                                    height: 210.0,
                                    child: GeneratedGroup166Widget(),
                                  ),
                                  Positioned(
                                    left: 210.0,
                                    top: 140.0,
                                    right: null,
                                    bottom: null,
                                    width: 120.0,
                                    height: 120.0,
                                    child: GeneratedImage2Widget(),
                                  ),
                                  Positioned(
                                    left: 200.0,
                                    top: 269.0,
                                    right: null,
                                    bottom: null,
                                    width: 118.0,
                                    height: 13.0,
                                    child:
                                        GeneratedFrozenFoodBaksoLurahWidget(),
                                  ),
                                  Positioned(
                                    left: 200.0,
                                    top: 279.0,
                                    right: null,
                                    bottom: null,
                                    width: 113.0,
                                    height: 12.0,
                                    child:
                                        GeneratedBaksocurahBerat500gramWidget(),
                                  ),
                                  Positioned(
                                    left: 150.0,
                                    top: 370.0,
                                    right: null,
                                    bottom: null,
                                    width: 120.0,
                                    height: 120.0,
                                    child: GeneratedImage3Widget(),
                                  ),
                                  Positioned(
                                    left: 20.0,
                                    top: 510.0,
                                    right: null,
                                    bottom: null,
                                    width: 125.0,
                                    height: 12.0,
                                    child:
                                        GeneratedTempuraFoodyBerat500gramWidget(),
                                  ),
                                  Positioned(
                                    left: 11.0,
                                    top: 570.0,
                                    right: null,
                                    bottom: null,
                                    width: 160.0,
                                    height: 210.0,
                                    child: GeneratedGroup196Widget(),
                                  ),
                                  Positioned(
                                    left: 190.0,
                                    top: 800.0,
                                    right: null,
                                    bottom: null,
                                    width: 160.0,
                                    height: 210.0,
                                    child: GeneratedGroup201Widget(),
                                  ),
                                  Positioned(
                                    left: 11.0,
                                    top: 800.0,
                                    right: null,
                                    bottom: null,
                                    width: 160.0,
                                    height: 210.0,
                                    child: GeneratedGroup200Widget(),
                                  ),
                                  Positioned(
                                    left: 190.0,
                                    top: 570.0,
                                    right: null,
                                    bottom: null,
                                    width: 160.0,
                                    height: 210.0,
                                    child: GeneratedGroup197Widget(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 140.0,
                                    right: null,
                                    bottom: null,
                                    width: 121.0,
                                    height: 120.0,
                                    child: GeneratedImage3Widget1(),
                                  ),
                                  Positioned(
                                    left: 190.0,
                                    top: 340.0,
                                    right: null,
                                    bottom: null,
                                    width: 160.0,
                                    height: 210.0,
                                    child: GeneratedGroup176Widget(),
                                  ),
                                  Positioned(
                                    left: 210.0,
                                    top: 600.0,
                                    right: null,
                                    bottom: null,
                                    width: 120.0,
                                    height: 120.0,
                                    child: GeneratedImage18Widget(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 830.0,
                                    right: null,
                                    bottom: null,
                                    width: 120.0,
                                    height: 120.0,
                                    child: GeneratedImage19Widget(),
                                  ),
                                  Positioned(
                                    left: 210.0,
                                    top: 830.0,
                                    right: null,
                                    bottom: null,
                                    width: 120.0,
                                    height: 120.0,
                                    child: GeneratedImage20Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: null,
              right: null,
              bottom: 0.0,
              width: 360.0,
              height: 60.0,
              child: GeneratedFuterWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 60.0,
              child: GeneratedHeaderWidget(),
            )
          ]),
    ));
  }
}
