import 'package:flutter/material.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedGroup103Widget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedImage11Widget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedImage14Widget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedVectorWidget34.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedKonfirmasiWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedGroup63Widget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedCODWidget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedMetodepembayaranWidget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedRectangle58Widget4.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedGroup65Widget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedGroup64Widget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedGroup102Widget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedShopeepayWidget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedImage13Widget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedMbankingWidget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedOVOWidget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedGroup66Widget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedImage15Widget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedGopayWidget.dart';
import 'package:flutterapp/frezzemeapp/generated10metodepembayaranuserwidget/generated/GeneratedImage16Widget.dart';

/* Frame 10. Metode Pembayaran user
    Autogenerated by FlutLab FTF Generator
  */
class Generated10MetodePembayaranuserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 11.988304138183594,
                top: 80.0,
                right: null,
                bottom: null,
                width: 338.0116882324219,
                height: 40.0,
                child: GeneratedGroup64Widget(),
              ),
              Positioned(
                left: 10.994152069091797,
                top: 140.0,
                right: null,
                bottom: null,
                width: 339.005859375,
                height: 40.0,
                child: GeneratedGroup65Widget(),
              ),
              Positioned(
                left: 10.994152069091797,
                top: 200.0,
                right: null,
                bottom: null,
                width: 339.005859375,
                height: 40.0,
                child: GeneratedGroup66Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 40.0,
                child: GeneratedGroup63Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedRectangle58Widget4(),
              ),
              Positioned(
                left: 49.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 20.0,
                child: GeneratedMetodepembayaranWidget(),
              ),
              Positioned(
                left: 143.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 23.0,
                child: GeneratedKonfirmasiWidget(),
              ),
              Positioned(
                left: 10.994152069091797,
                top: 260.0,
                right: null,
                bottom: null,
                width: 339.005859375,
                height: 40.0,
                child: GeneratedGroup102Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 40.0,
                child: GeneratedGroup103Widget(),
              ),
              Positioned(
                left: 78.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 20.0,
                child: GeneratedOVOWidget(),
              ),
              Positioned(
                left: 78.0,
                top: 153.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 20.0,
                child: GeneratedGopayWidget(),
              ),
              Positioned(
                left: 78.0,
                top: 333.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 20.0,
                child: GeneratedCODWidget(),
              ),
              Positioned(
                left: 77.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 17.0,
                child: GeneratedMbankingWidget(),
              ),
              Positioned(
                left: 78.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 17.0,
                child: GeneratedShopeepayWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06388888888888888;
                  double scaleX = (constraints.maxWidth * percentWidth) / 23.0;

                  double percentHeight = 0.0296875;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.0328125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget34())
                  ]);
                }),
              ),
              Positioned(
                left: 16.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 10.0,
                child: GeneratedImage11Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedImage13Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 31.0,
                child: GeneratedImage14Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedImage15Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 147.0,
                right: null,
                bottom: null,
                width: 43.0,
                height: 26.0,
                child: GeneratedImage16Widget(),
              )
            ]),
      ),
    ));
  }
}
