import 'package:flutter/material.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedRectangle148Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedSosisBestoBerat500gramWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedGroup120Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedGroup150Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedGroup144Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratediconshoppingcartoutlineWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedGroup142Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedGroup151Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedAdamalik21Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedRectangle97Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedWishlistWidget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedRectangle147Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedFrozenFoodSosisBakarBestoWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedVectorWidget73.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedAdamalik21gmailcomWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedGroup147Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedRectangle103Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedRiwayatPembelianWidget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedImage10Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/Generated1122022Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedLine150Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedBaksoCurahBerat500gramWidget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedAkunSayaWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedFrozenFoodBaksoCurahWidget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedImage6Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedBeliWidget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratediconpersonWidget2.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedImage4Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedKeranjangBelanjaWidget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedGroup111Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/Generated1892022Widget.dart';
import 'package:flutterapp/frezzemeapp/generated15akunsayawidget/generated/GeneratedPostinganWidget.dart';

/* Frame 15. Akun Saya
    Autogenerated by FlutLab FTF Generator
  */
class Generated15AkunSayaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 121.0,
                child: GeneratedRectangle97Widget(),
              ),
              Positioned(
                left: -5.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 124.0,
                child: GeneratedImage10Widget(),
              ),
              Positioned(
                left: 301.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 20.0,
                child: GeneratedGroup111Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedGroup142Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 20.0,
                child: GeneratedAkunSayaWidget1(),
              ),
              Positioned(
                left: 237.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 20.0,
                child: GeneratedGroup144Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 170.0,
                child: GeneratedGroup147Widget(),
              ),
              Positioned(
                left: 81.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 22.0,
                child: GeneratedBeliWidget(),
              ),
              Positioned(
                left: 211.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 22.0,
                child: GeneratedPostinganWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 1.0,
                child: GeneratedLine150Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 15.0,
                child: GeneratedKeranjangBelanjaWidget(),
              ),
              Positioned(
                left: 229.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 18.0,
                child: GeneratedWishlistWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 170.0,
                child: GeneratedRectangle103Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 387.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 16.0,
                child: GeneratedRiwayatPembelianWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 60.0,
                child: GeneratedGroup120Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 411.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 60.0,
                child: GeneratedGroup151Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 60.0,
                child: GeneratedGroup150Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06388888888888888;
                  double scaleX = (constraints.maxWidth * percentWidth) / 23.0;

                  double percentHeight = 0.0296875;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.0328125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget73())
                  ]);
                }),
              ),
              Positioned(
                left: 70.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 22.0,
                child: GeneratedAdamalik21Widget(),
              ),
              Positioned(
                left: 70.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 20.0,
                child: GeneratedAdamalik21gmailcomWidget1(),
              ),
              Positioned(
                left: 40.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedImage6Widget1(),
              ),
              Positioned(
                left: 40.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedImage4Widget1(),
              ),
              Positioned(
                left: 90.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 14.0,
                child: GeneratedFrozenFoodSosisBakarBestoWidget1(),
              ),
              Positioned(
                left: 90.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 14.0,
                child: GeneratedFrozenFoodBaksoCurahWidget(),
              ),
              Positioned(
                left: 90.0,
                top: 435.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 21.0,
                child: GeneratedSosisBestoBerat500gramWidget1(),
              ),
              Positioned(
                left: 90.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 21.0,
                child: GeneratedBaksoCurahBerat500gramWidget(),
              ),
              Positioned(
                left: 240.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 12.0,
                child: Generated1122022Widget(),
              ),
              Positioned(
                left: 240.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 12.0,
                child: Generated1892022Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.14444444444444443;

                  final double height = constraints.maxHeight * 0.08125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.025,
                        y: constraints.maxHeight * 0.1328125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconpersonWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 70.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 80.0,
                child: GeneratedRectangle147Widget(),
              ),
              Positioned(
                left: 210.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 77.0,
                height: 80.0,
                child: GeneratedRectangle148Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.5305555555555556;

                  final double height = constraints.maxHeight * 0.078125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2361111111111111,
                        y: constraints.maxHeight * 0.3828125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconshoppingcartoutlineWidget3(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
