import 'package:flutter/material.dart';

/* UndefinedNode Daftar Guest
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDaftarGuestWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
