import 'package:flutter/material.dart';

/* UndefinedNode Masuk User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMasukUserWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
