import 'package:flutter/material.dart';
import 'package:flutterapp/frezzemeapp/generated18logoutwidget/generated/GeneratedGroup175Widget.dart';
import 'package:flutterapp/frezzemeapp/generated18logoutwidget/generated/GeneratedApakahAndaYakinLogoutSebagaiUserWidget.dart';
import 'package:flutterapp/frezzemeapp/generated18logoutwidget/generated/GeneratedRectangle91Widget.dart';
import 'package:flutterapp/frezzemeapp/generated18logoutwidget/generated/GeneratedGroup157Widget.dart';
import 'package:flutterapp/frezzemeapp/generated18logoutwidget/generated/GeneratedGroup156Widget.dart';

/* Frame 18. Logout
    Autogenerated by FlutLab FTF Generator
  */
class Generated18LogoutWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 73.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 40.0,
                child: GeneratedApakahAndaYakinLogoutSebagaiUserWidget(),
              ),
              Positioned(
                left: 136.0,
                top: 339.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 20.0,
                child: GeneratedGroup157Widget(),
              ),
              Positioned(
                left: 190.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 17.0,
                child: GeneratedGroup156Widget(),
              ),
              Positioned(
                left: 70.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 100.0,
                child: GeneratedGroup175Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedRectangle91Widget(),
              )
            ]),
      ),
    ));
  }
}
