import 'package:flutter/material.dart';

/* UndefinedNode Wishlist 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWishlist1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
