import 'package:flutter/material.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedImage4Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedFrozenFoodBaksoLurahWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedFrozenFoodTempuraFoodyWidget2.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedImage11Widget3.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratediconarrowiosdownwardWidget.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedGroup153Widget.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedPostinganWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedGroup154Widget.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedFrozenFoodTempuraFoodyWidget3.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedImage11Widget2.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedGroup152Widget.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedFrozenFoodSosisBakarBestoWidget2.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratediconpersonWidget3.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedBeliWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedImage5Widget2.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedVectorWidget85.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedBaksoCurahBerat500gramWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedLine150Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedTempuraFoodyBerat500gramWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedAdamalik21Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedBaksoIkanBerat500gramWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedGroup147Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedAdamalik21gmailcomWidget2.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedRectangle97Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedGroup146Widget.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedImage11Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratediconarrowiosdownwardWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedSosisBestoBerat500gramWidget2.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedAkunSayaWidget2.dart';
import 'package:flutterapp/frezzemeapp/generated16akunsayawidget/generated/GeneratedRectangle148Widget1.dart';

/* Frame 16. Akun Saya
    Autogenerated by FlutLab FTF Generator
  */
class Generated16AkunSayaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -5.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 121.0,
                child: GeneratedRectangle97Widget1(),
              ),
              Positioned(
                left: 10.0,
                top: 410.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 210.0,
                child: GeneratedGroup146Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 210.0,
                child: GeneratedGroup147Widget1(),
              ),
              Positioned(
                left: 81.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 22.0,
                child: GeneratedBeliWidget1(),
              ),
              Positioned(
                left: 211.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 22.0,
                child: GeneratedPostinganWidget1(),
              ),
              Positioned(
                left: 210.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 1.0,
                child: GeneratedLine150Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05277777777777778;

                  final double height = constraints.maxHeight * 0.015625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8361111111111111,
                        y: constraints.maxHeight * 0.4375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowiosdownwardWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05277777777777778;

                  final double height = constraints.maxHeight * 0.015625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8361111111111111,
                        y: constraints.maxHeight * 0.796875,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconarrowiosdownwardWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 30.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedImage11Widget1(),
              ),
              Positioned(
                left: 170.0,
                top: 230.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedImage11Widget2(),
              ),
              Positioned(
                left: 30.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 14.0,
                child: GeneratedFrozenFoodSosisBakarBestoWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 21.0,
                child: GeneratedSosisBestoBerat500gramWidget2(),
              ),
              Positioned(
                left: 170.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 14.0,
                child: GeneratedFrozenFoodBaksoLurahWidget1(),
              ),
              Positioned(
                left: 170.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 21.0,
                child: GeneratedBaksoCurahBerat500gramWidget1(),
              ),
              Positioned(
                left: 130.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 101.69491577148438,
                child: GeneratedImage4Widget2(),
              ),
              Positioned(
                left: 170.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 100.0,
                child: GeneratedImage5Widget2(),
              ),
              Positioned(
                left: 30.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 9.0,
                child: GeneratedFrozenFoodTempuraFoodyWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 79.0,
                height: 8.0,
                child: GeneratedTempuraFoodyBerat500gramWidget1(),
              ),
              Positioned(
                left: 170.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 9.0,
                child: GeneratedFrozenFoodTempuraFoodyWidget3(),
              ),
              Positioned(
                left: 170.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 68.0,
                height: 8.0,
                child: GeneratedBaksoIkanBerat500gramWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 121.0,
                child: GeneratedRectangle148Widget1(),
              ),
              Positioned(
                left: -6.0,
                top: -1.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 124.0,
                child: GeneratedImage11Widget3(),
              ),
              Positioned(
                left: 301.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 20.0,
                child: GeneratedGroup152Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 60.0,
                child: GeneratedGroup153Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 20.0,
                child: GeneratedAkunSayaWidget2(),
              ),
              Positioned(
                left: 237.0,
                top: 10.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 20.0,
                child: GeneratedGroup154Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06388888888888888;
                  double scaleX = (constraints.maxWidth * percentWidth) / 23.0;

                  double percentHeight = 0.0296875;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.0328125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget85())
                  ]);
                }),
              ),
              Positioned(
                left: 70.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 22.0,
                child: GeneratedAdamalik21Widget1(),
              ),
              Positioned(
                left: 70.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 20.0,
                child: GeneratedAdamalik21gmailcomWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.14444444444444443;

                  final double height = constraints.maxHeight * 0.08125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.025,
                        y: constraints.maxHeight * 0.1328125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconpersonWidget3(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
