import 'package:flutter/material.dart';

/* UndefinedNode Daftar Admin
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDaftarAdminWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
