import 'package:flutter/material.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedHaloSayapesanFrozenfoodSosisBakarnya1Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedZahraWidget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedRectangle84Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedHapusWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedImage6Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedImage8Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedHaloSayapesanFrozenfoodTempuraFoody2Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedBaraWidget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedRectangle76Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedRectangle88Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedGroup178Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedRectangle87Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedVectorWidget38.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedImage5Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedRectangle86Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedImage7Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedRectangle85Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedHapusWidget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedPesanWidget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedRectangle89Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedGroup70Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedGroup71Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedRectangle60Widget.dart';
import 'package:flutterapp/frezzemeapp/generated13pesanuserwidget/generated/GeneratedRectangle90Widget.dart';

/* Frame 13. Pesan user
    Autogenerated by FlutLab FTF Generator
  */
class Generated13PesanuserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 10.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 90.0,
                child: GeneratedGroup70Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 90.0,
                child: GeneratedGroup71Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedRectangle60Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedRectangle86Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedRectangle87Widget(),
              ),
              Positioned(
                left: -9.094947017729282e-13,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedRectangle76Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 23.0,
                child: GeneratedPesanWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 10.0,
                child: GeneratedRectangle84Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 10.0,
                child: GeneratedRectangle85Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 10.0,
                child: GeneratedRectangle88Widget(),
              ),
              Positioned(
                left: 310.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle89Widget(),
              ),
              Positioned(
                left: 310.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle90Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 13.0,
                child: GeneratedZahraWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 251.0,
                right: null,
                bottom: null,
                width: 21.0,
                height: 13.0,
                child: GeneratedBaraWidget(),
              ),
              Positioned(
                left: 309.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 13.0,
                child: GeneratedHapusWidget(),
              ),
              Positioned(
                left: 309.0,
                top: 241.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 13.0,
                child: GeneratedHapusWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06388888888888888;
                  double scaleX = (constraints.maxWidth * percentWidth) / 23.0;

                  double percentHeight = 0.0296875;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.058333333333333334,
                        translateY: constraints.maxHeight * 0.03125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget38())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedGroup178Widget(),
              ),
              Positioned(
                left: 314.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 18.0,
                child: GeneratedImage5Widget(),
              ),
              Positioned(
                left: 314.0,
                top: 220.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 18.0,
                child: GeneratedImage6Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 32.280189514160156,
                child: GeneratedImage7Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 36.77799987792969,
                child: GeneratedImage8Widget(),
              ),
              Positioned(
                left: 79.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 26.0,
                child: GeneratedHaloSayapesanFrozenfoodSosisBakarnya1Widget(),
              ),
              Positioned(
                left: 79.0,
                top: 210.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 26.0,
                child: GeneratedHaloSayapesanFrozenfoodTempuraFoody2Widget(),
              )
            ]),
      ),
    ));
  }
}
