import 'package:flutter/material.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedVectorWidget49.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedGroup70Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedRectangle85Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedRectangle89Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedRectangle86Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedImage5Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedHapusWidget2.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedHaloSayapesanFrozenfoodTempuraFoody2Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedImage8Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedRectangle60Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedBaraWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedRectangle84Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedRectangle76Widget1.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedPesanWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated14pesanwidget/generated/GeneratedGroup178Widget1.dart';

/* Frame 14. Pesan
    Autogenerated by FlutLab FTF Generator
  */
class Generated14PesanWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 10.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 90.0,
                child: GeneratedGroup70Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedRectangle60Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedRectangle86Widget1(),
              ),
              Positioned(
                left: -9.094947017729282e-13,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedRectangle76Widget1(),
              ),
              Positioned(
                left: 49.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 23.0,
                child: GeneratedPesanWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 10.0,
                child: GeneratedRectangle84Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 10.0,
                child: GeneratedRectangle85Widget1(),
              ),
              Positioned(
                left: 310.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedRectangle89Widget1(),
              ),
              Positioned(
                left: 32.0,
                top: 151.0,
                right: null,
                bottom: null,
                width: 21.0,
                height: 13.0,
                child: GeneratedBaraWidget1(),
              ),
              Positioned(
                left: 309.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 13.0,
                child: GeneratedHapusWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06388888888888888;
                  double scaleX = (constraints.maxWidth * percentWidth) / 23.0;

                  double percentHeight = 0.0296875;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.058333333333333334,
                        translateY: constraints.maxHeight * 0.03125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget49())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedGroup178Widget1(),
              ),
              Positioned(
                left: 314.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 13.0,
                height: 18.0,
                child: GeneratedImage5Widget1(),
              ),
              Positioned(
                left: 27.0,
                top: 102.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 36.77799987792969,
                child: GeneratedImage8Widget1(),
              ),
              Positioned(
                left: 80.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 26.0,
                child: GeneratedHaloSayapesanFrozenfoodTempuraFoody2Widget1(),
              )
            ]),
      ),
    ));
  }
}
