import 'package:flutter/material.dart';

/* UndefinedNode Love Wishlist
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoveWishlistWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
