import 'package:flutter/material.dart';

/* UndefinedNode Masuk Admin
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMasukAdminWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
