import 'package:flutter/material.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/Generatediconedit2outlineWidget.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedVectorWidget60.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedAkunSayaWidget.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedGroup139Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratediconimageWidget.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedNomorHandponeWidget.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedNamaPenggunaWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedAdamalik21gmailcomWidget.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedGroup135Widget.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/Generatediconedit2outlineWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedAdamaliik21Widget.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedRectangle82Widget.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedEmailWidget2.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratediconpersonWidget1.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedGroup136Widget.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/Generated0853Widget.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedRectangle80Widget.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/frezzemeapp/generated17akunsayawidget/generated/GeneratedRectangle81Widget.dart';

/* Frame 17. Akun Saya
    Autogenerated by FlutLab FTF Generator
  */
class Generated17AkunSayaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 120.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 120.0,
                child: GeneratedEllipse9Widget(),
              ),
              Positioned(
                left: 130.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 20.0,
                child: GeneratedGroup139Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 20.0,
                child: GeneratedRectangle80Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 20.0,
                child: GeneratedRectangle81Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 21.0,
                child: GeneratedRectangle82Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 17.0,
                child: GeneratedEmailWidget2(),
              ),
              Positioned(
                left: 20.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 14.0,
                child: GeneratedNamaPenggunaWidget1(),
              ),
              Positioned(
                left: 20.0,
                top: 283.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 14.0,
                child: GeneratedNomorHandponeWidget(),
              ),
              Positioned(
                left: 321.0,
                top: 271.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 10.0,
                child: GeneratedGroup135Widget(),
              ),
              Positioned(
                left: 322.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 10.0,
                child: GeneratedGroup136Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 21.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 20.0,
                child: GeneratedAkunSayaWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.06388888888888888;
                  double scaleX = (constraints.maxWidth * percentWidth) / 23.0;

                  double percentHeight = 0.0296875;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 19.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.05555555555555555,
                        translateY: constraints.maxHeight * 0.0328125,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget60())
                  ]);
                }),
              ),
              Positioned(
                left: 30.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 18.0,
                child: GeneratedAdamaliik21Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 18.0,
                child: Generated0853Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 17.0,
                child: GeneratedAdamalik21gmailcomWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2638888888888889;

                  final double height = constraints.maxHeight * 0.1484375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.36666666666666664,
                        y: constraints.maxHeight * 0.125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconpersonWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.07222222222222222;

                  final double height = constraints.maxHeight * 0.040625;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.6527777777777778,
                        y: constraints.maxHeight * 0.3078125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratediconimageWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05555555555555555;

                  final double height = constraints.maxHeight * 0.03125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8861111111111111,
                        y: constraints.maxHeight * 0.390625,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generatediconedit2outlineWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.05555555555555555;

                  final double height = constraints.maxHeight * 0.03125;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8861111111111111,
                        y: constraints.maxHeight * 0.453125,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generatediconedit2outlineWidget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
