import 'package:flutter/material.dart';

/* Text USER
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUSERWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''USER''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.2102272620567909,
        fontSize: 65.0,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w800,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
