import 'package:flutter/material.dart';

/* UndefinedNode Rating Bintang
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRatingBintangWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
